# Generated by Django 5.2.1 on 2025-05-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
