# Generated by Django 5.2.1 on 2025-05-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
