# Generated by Django 5.2.1 on 2025-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_category_id_alter_clothes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='quantity_in_stock',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=10),
        ),
    ]
