# Generated by Django 5.2.1 on 2025-05-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='user',
        ),
    ]
