# Generated by Django 5.2.1 on 2025-05-14 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_alter_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Đang chuẩn bị', 'Đang chuẩn bị'), ('Đang giao', 'Đang giao'), ('Hoàn thành', 'Hoàn thành'), ('Hủy', 'Hủy')], default='Đang chuẩn bị', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hovaten', models.CharField(blank=True, max_length=200, null=True)),
                ('sdt', models.CharField(blank=True, max_length=12, null=True)),
                ('diachi', models.CharField(blank=True, max_length=255, null=True)),
                ('tongtien', models.FloatField(default=0.0)),
                ('products', models.ManyToManyField(blank=True, to='clothes.clothes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('total_value', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
            ],
        ),
    ]
