# Generated by Django 5.2.1 on 2025-05-14 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_alter_cart_id_alter_cartitem_id_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('methodname', models.CharField(choices=[('COD', 'COD'), ('QRPay', 'QRPay')], default='COD', max_length=20)),
                ('QRcode', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đang chuẩn bị', 'Đang chuẩn bị'), ('Đang giao', 'Đang giao'), ('Hoàn thành', 'Hoàn thành'), ('Hủy', 'Hủy')], default='Chờ xác nhận', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clothes.paymentmethod'),
            preserve_default=False,
        ),
    ]
