# Generated by Django 5.2.1 on 2025-05-15 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_alter_order_tongtien_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='clothes.clothes', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng loại sản phẩm'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.cart', verbose_name='Giỏ hàng'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.category', verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.URLField(verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='quantity_in_stock',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='SL trong kho'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='status',
            field=models.CharField(choices=[('còn hàng', 'còn hàng'), ('hết hàng', 'hết hàng')], default='còn hàng', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
